server:
  port: 18081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.40.153:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: jyzx1
    password: jyzx1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 1
      connection-test-query: SELECT 1 FROM DUAL
      idle-timeout: 10000
      validation-timeout: 10000
  redis:
    host: 127.0.0.1
    port: 6379
    password: dms@0712
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 10
        min-idle: 10
        max-idle: 10
  elasticsearch:
    rest:
      uris:
        - "http://192.168.40.221:9200"
        - "http://192.168.40.222:9200"
        - "http://192.168.40.223:9200"
      username: elastic
      password: 123456
  jackson:
    default-property-inclusion: non_empty
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.xwtec.entity
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
    config: classpath:log4j2-config-${spring.profiles.active}.yml
