Configuration:
  status: DEBUG
  monitorInterval: 30

  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：

  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: DEBUG
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%clr{%d{yyyy-MM-dd HH:mm:ss.SSS}}{faint} %clr{%5p} %clr{---}  %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n%xwEx"

  Loggers:
    AsyncRoot:
      level: DEBUG
      AppenderRef:
        - ref: CONSOLE
    AsyncLogger: # 为com.xwtech包配置特殊的Log级别，方便调试
      - name: com.xwtech
        additivity: false
        level: DEBUG
        AppenderRef:
          - ref: CONSOLE
      - name: org.springframework
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
      - name: org.apache.http
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE